istio-ecosystem/authservice

- CONTRIBUTING.md
Adding clarifications on expectations from contributors.
> Added contributing instructions file, clarifying the CLA requirements.

- OWNERS
Adding OWNERS file for prow input.
I am also using this PR to test istio-testing bot.
/hold
> Adding OWNERS file to authservice repo

- WORKSPACE
- build/Dockerfile.builder
- build/install-bazel.sh
- src/filters/BUILD
- src/service/BUILD
- test/filters/BUILD
- test/filters/oidc/BUILD
- Updated envoy reference from Thales fork to envoy mainline.
- Refactored WORKSPACE
> Envoy ref update

- src/filters/oidc/oidc_filter.cc
- test/filters/oidc/oidc_filter_test.cc
> Add the prefix "Bearer " to the Authorization header

- OWNERS
This OWNERS file was not properly formatted and was not being parsed by Prow.
/assign @BrenoDeMedeiros @liminw @sawlanipradeep @icygalz
> Fix invalid OWNERS file.

- README.md
- bookinfo-example/README.md
- bookinfo-example/config/bookinfo-gateway.yaml
- bookinfo-example/config/bookinfo-with-authservice-template.yaml
- Add list of features
- Add link to flowchart diagram (which we also updated)
> Improve readme

- src/common/http/http.cc
> Always ignore stream_truncated errors from async_shutdown

- config/oidc/config.proto
- src/common/http/http.cc
- src/common/http/http.h
- src/config/get_config.cc
- src/filters/oidc/oidc_filter.cc
- test/common/http/http_test.cc
- test/common/http/mocks.h
- test/config/getconfig_test.cc
- test/filters/oidc/oidc_filter_test.cc
- test/fixtures/valid-config.json
> Support sending requests through a web proxy

- bookinfo-example/README.md
> Minor fixes to bookinfo-example/README.md

- src/service/async_service_impl.cc
Fixes #112
Not going to go into details here, please reference original issue.
We have been running this change in prod for a while now with no issues.
Only question is if we want to just remove that block of code entirely or leave that logging as is.
> Fix Run: Unexpected error: !ok

- OWNERS
https://github.com/istio-ecosystem/authservice/pull/124#issuecomment-767864532
> Add lizan and zack to OWNERS

- bookinfo-example/README.md
Signed-off-by: Shikugawa <Shikugawa@gmail.com>
> add additional useful infomation on bookinfo example docs

- src/filters/BUILD
- src/filters/filter_chain.cc
- src/filters/filter_chain.h
- src/filters/filter_factory.h
- src/filters/mock/BUILD
- src/filters/mock/mock_filter.cc
- src/filters/mock/mock_filter.h
- src/filters/oidc/BUILD
- src/filters/oidc/in_memory_session_store.cc
- src/filters/oidc/in_memory_session_store.h
- src/filters/oidc/jwks_resolver.h
- src/filters/oidc/oidc_filter.cc
- src/filters/oidc/oidc_filter.h
- src/filters/oidc/redis_session_store.cc
- src/filters/oidc/redis_session_store.h
- src/filters/oidc/session_store.h
- src/filters/oidc/session_store_factory.h
Signed-off-by: Shikugawa <Shikugawa@gmail.com>
> filter and session store abstraction and filter chain refactor

- bookinfo-example/authservice/templates/config.yaml
- bookinfo-example/authservice/templates/deployment.yaml
> Fix the authservice httpGet probe config and use jwks_uri.

- .github/workflows/workflow.yml
- WORKSPACE
- bazel/bazel.bzl
- bazel/install-clang-ci.sh
- build/Dockerfile.build
- src/common/http/BUILD
- src/common/session/BUILD
- src/common/utilities/BUILD
- src/config/BUILD
- src/filters/BUILD
- src/filters/mock/BUILD
- src/filters/oidc/BUILD
- src/main/BUILD
- src/service/BUILD
- test/common/http/BUILD
- test/common/session/BUILD
- test/common/utilities/BUILD
- test/config/BUILD
- test/filters/BUILD
- test/filters/oidc/BUILD
- test/service/BUILD
- test/shared/BUILD
https://github.com/istio-ecosystem/authservice/issues/197
> Enable CI for clang with FIPS mode.

- src/common/http/http.cc
- src/common/http/http.h
- src/filters/oidc/jwks_resolver.cc
- src/filters/oidc/oidc_filter.cc
- test/common/http/mocks.h
- test/filters/oidc/jwks_resolver_test.cc
- test/filters/oidc/oidc_filter_test.cc
> add option to disable remote ca verify

- .github/workflows/release.yaml
- test/exe/require_static.sh
> Fix github access token naming.

- .github/workflows/release.yaml
As suggested by @dio 
https://github.com/istio-ecosystem/authservice/commit/28404a8f3f9e11ff14e81d6650ffc72245355653#commitcomment-70845200
> Move the VERSION env to GITHUB_ENV.

- src/service/BUILD
- src/service/async_service_impl.h
leftover comment from https://github.com/istio-ecosystem/authservice/pull/223/files
> clean the commented out code.

- go.mod
- go.sum
Fixes https://github.com/istio-ecosystem/authservice/security/dependabot/5
> Fix CVE-2024-45338

- go.mod
Fixes https://github.com/istio-ecosystem/authservice/security/code-scanning/8
> Bump Go to fix CVE-2025-22866

- internal/logr.go
- internal/logr_test.go
Fixes the logging bridge configuration as it was not properly honoring the logging level configuration.
> fix logr configuration

- go.mod
Fixes https://github.com/istio-ecosystem/authservice/security/code-scanning/11
Fixes https://github.com/istio-ecosystem/authservice/security/code-scanning/12
Fixes https://github.com/istio-ecosystem/authservice/security/code-scanning/10
> CVE: bump golang to 1.24.4 to fix several CVEs
