- src/filters/oidc/oidc_filter.cc
- test/filters/oidc/oidc_filter_test.cc
Unclear why the request has no scheme, so perhaps we can revisit this later. For now, skipping the scheme comparison seems okay since the app should be configured to only allow https traffic for the alpha release anyway.
Resolves #24
> The check()'s request has no scheme, so don't rely on it

- Makefile
- build/Dockerfile.interactive-compile-environment
There are link errors when compiled on MacOS, so make it easier
to compile in a system-independent way by providing a dockerfile
for building an image which contains all of the tools needed to
compile and test the project from an interactive shell inside
the container
> New dockerfile for system-independent compilation

- Makefile
- WORKSPACE
- build/Dockerfile.builder
- build/install-bazel.sh
- config/oidc/config.proto
- docker-compose.yml
- src/common/http/headers.h
- src/common/session/token_encryptor.cc
- src/filters/oidc/BUILD
- src/filters/oidc/oidc_filter.cc
- src/filters/oidc/oidc_filter.h
- src/filters/oidc/token_response.cc
- src/filters/oidc/token_response.h
- test/config/getconfig_test.cc
- test/filters/oidc/mocks.h
- test/filters/oidc/oidc_filter_test.cc
- test/filters/oidc/token_response_test.cc
- test/fixtures/valid-config.json
Fixing most of the necessary TODOs.
- Fixes validation of `nonce` and `aud` JWT fields at token acquisition time.
- Added `Max-Age` attributes to cookies.
- Removed invalid or won't-do TODOs.
fixes #33 
Any remaining TODOs can be done at a later date or will be fixed by other issues.
> 33 fix todos

- build/Dockerfile.builder
- build/Dockerfile.runner
- src/common/http/http.cc
Enables TLS peer verification for connection to upstream IDP services, to ensure the connections are secure. Also adds standard ca_certificates package to the Docker images which is required for verification of the certificate chains.
> Enable TLS peer verification and add CA root certificates to Docker images

- src/filters/oidc/oidc_filter.cc
- test/filters/oidc/oidc_filter_test.cc
Cause Envoy to return 400 status code when accessing callback url
when session is expired. This may happen if the user is redirected to
the IdP and takes more time to log in than the session timeout
Fixes https://github.com/istio-ecosystem/authservice/issues/91
Signed-off-by: Tyler Schultz <tschultz@pivotal.io>
> Envoy to return 400 status instead of dropping request

- config/config.proto
The initial part of adding global filter chain configuration. #132
It allows for users to set global configuration that will be applied to all filters in the same filter chain.
> Add global filter chain configuration API part 1

- src/config/BUILD
- src/config/get_config.cc
- test/config/getconfig_test.cc
Close #141 
In this PR, we fix the previous behavior which treat specified ID token header as case-sensitive. It is not required behavior and if we set `Authorization` as this. We will skip token check because ext_authz passes lower cased HTTP header value.
> fix to treat IDToken header as case-insensitive

- Makefile
- bookinfo-example/README.md
- bookinfo-example/config/authservice-configmap-template-for-authn.yaml
- bookinfo-example/config/bookinfo-gateway.yaml
- bookinfo-example/config/bookinfo-with-authservice-template.yaml
- bookinfo-example/config/productpage-external-authz-envoyfilter-sidecar.yaml
- bookinfo-example/scripts/generate-self-signed-certs-for-ingress-gateway.sh
- src/filters/filter_chain.cc
This PR updates a few things.
- Use external authz provider, the CUSTOM action.
- Change to use credentialName instead of mounting secrets for ingress to host the OIDC callback URI.
- Other misc polishment such as logging the jwks parsing error and makefile IMAGE customization.
> Update authservice using external authz.

- bookinfo-example/README.md
- bookinfo-example/authservice/templates/ext-authz.yaml
- bookinfo-example/authservice/templates/gateway.yaml
- bookinfo-example/authservice/values.yaml
Signed-off-by: Jianfei Hu <jianfeih@tetrate.io>
Fix #https://github.com/istio-ecosystem/authservice/issues/149
> Update values.yaml for different oidc enforcing mode.

- test/common/http/mocks.h
- test/common/utilities/mocks.h
- test/filters/oidc/mocks.h
Signed-off-by: Shikugawa <Shikugawa@gmail.com>
We should utilize un-numbered mock helpers like envoy.
> replace numbered mock helper with un-numbered one

- src/service/async_service_impl.cc
- src/service/async_service_impl.h
The reason for the OOM was that the ProcessingState pointer passed to CompletionState was not released properly. As a result of the fix, the memory pressure is as follows The load test was done as follows for bookinfo deployed in GKE.
```
fortio load -H ${COOKIE} -qps 800 -t 6m -c 4 https://${AUTHORITY_NAME}/productpage
```
```
fortio load -H ${COOKIE} -qps 6000 -t 6m -c 4 https://${AUTHORITY_NAME}/productpage
```
> fix OOM while processing gRPC completion state

- .bazelrc
- .gitignore
- README.md
- bazel/BUILD.boost
- bazel/boost.bzl
- bazel/setup_clang.sh
#192 
FIPS boringssl requires clang to compile. This is the first step to setup the clang copmilation option.
> Add clang.bazelrc setup from envoy.

- Makefile
- README.md
- build/Dockerfile.build
- build/Dockerfile.builder
https://github.com/istio-ecosystem/authservice/issues/192. The PR covers:
1. Separate the build env docker image (Dockerfile.builder) with the actual building process and artficat dockerfile (Dockerfile.build)
2. In the dockerfile.builder installs the llvm 12.0.
3. necessary readme.md and the makefile change.
To test this PR, you can
```
gh pr checkout https://github.com/istio-ecosystem/authservice/pull/196
docker build --build-arg bazel_flags="--config=clang --define boringssl=fips" \
-t ${CONTAINER_REGISTRY}/authservice:latest \
-f ./build/Dockerfile.build .
```
> Make it possible to run clang/fips build in container.

- Makefile
- src/common/http/http.cc
- test/common/http/http_test.cc
Fix https://github.com/istio-ecosystem/authservice/issues/205
> Fix url encoding handling for code parameter.

- src/common/http/http.cc
- test/common/http/http_test.cc
Fixes https://github.com/istio-ecosystem/authservice/issues/211
After this PR, the issue is resolved.
> Change to shutdown the connection directly in case the server do not participate close.

- .github/workflows/commit.yaml
- .github/workflows/release.yaml
- Dockerfile
- Makefile
- bazel/bazel.bzl
- test/exe/require_static.sh
This patch makes sure we do: "-static-libgcc" on Linux (for the stripped binary). We also use `--config libc++` (instead of `--config clang`) to link against `libc++` on CI (Linux).
This also adds a workflow to publish the Docker image. 
> Append -static-libgcc on Linux

- src/common/http/http.cc
Seems like this error can be ignored. References:
1. https://jira.mongodb.org/browse/TOOLS-1906?jql=Participants%20%3D%20kanant
2. https://github.com/facebook/folly/blob/d3354e2282303402e70d829d19bfecce051a5850/folly/ssl/OpenSSLCertUtils.cpp#L367-L368
> Skip X509_R_CERT_ALREADY_IN_HASH_TABLE error

- bookinfo-example/authservice/templates/config.yaml
- src/service/BUILD
- src/service/async_service_impl.cc
- src/service/async_service_impl.h
Fix #140 
Previously we only return the grpc status, but not set the actual response payload, `response.status`.
Verified works manually e2e with `allow_unmatched_request: true/false` having different effect.
> Fix the unmatched request handling by set the grpc status in payload.

- bazel/repositories.bzl
- bazel/rules_boost.patch
This makes sure we use @envoy//bazel:boringssl.
> Use @envoy//bazel:boringssl

- src/common/http/http.cc
The previous error checking was wrong, since
ctx.add_certificate_authority is already done the ERR_get_error. The relevant SSL error should be wrapped as system::error_code.
> http: Ignore X509_R_CERT_ALREADY_IN_HASH_TABLE

- .github/workflows/commit.yaml
- .github/workflows/release.yaml
- Makefile
The FIPS mode is only relevant for clang and Linux x68_64.
> Enable FIPS for Linux only

- e2e/istio/Makefile
- e2e/istio/suite_test.go
Currently, the e2e test suite runs against the latest Istio version. This change allows setting the `E2E_ISTIO_VERSION` to the version of Istio to be used. If left empty (default) the latest Istio version will still be installed.
It can be used as:
```bash
E2E_ISTIO_VERSION=1.21.0 E2E_TEST_OPTS=-v make e2e/istio
```
> Allow customizing the Istio version to use in the e2e tests

- go.mod
Upgrade to the latest version of Go to get rid of CVE-2023-45288 in our docker images.
> Upgrade Go to 1.22.2 to get rid of CVE-2023-45288

- internal/authz/oidc.go
- internal/authz/oidc_test.go
This handles cases where the JWS message or the key do not have a proper `alg` header. The `alg` header is [optional](https://datatracker.ietf.org/doc/html/rfc7517#section-4.4), so some identity providers may not supply it (such as [Microsoft Identity](https://login.microsoftonline.com/common/discovery/v2.0/keys)).
> Infer the JWS signing algorithm name by looking at the provided key

- e2e/istio/istio_test.go
- e2e/keycloak/keycloak_test.go
- e2e/legacy/legacy_test.go
- e2e/testclient.go
- internal/authz/oidc.go
- internal/authz/oidc_test.go
- internal/http/http.go
- internal/http/http_test.go
- internal/http/logging.go
- internal/http/logging_test.go
- internal/logging.go
- internal/logging_test.go
- internal/oidc/jwks.go
- internal/oidc/memory.go
- internal/oidc/redis.go
This adds the `idp` logger that will log all the calls made to the Identity Provider such as the token endpoint calls. It also adds more information to some of the existing loggers. Currently, there are no means to see what requests are being made as part of the OIDC flow, and troubleshooting the responses from the IdP was challenging. This logger will facilitate better understand the flow.
It is important to note that the `idp` logger may expose sensitive information in the logs, such as the `client_secret` or the tokens being issued. Use with care and do not enable it by default. To make it easier to set default log levels and just override some, I've changed a bit the behavior of the logging settings, to allow things like: `all:debug,idp:none`. Previously, if the `all` logger was set, …
> Add a logger to log the calls to the Identity Provider

- internal/authz/oidc_test.go
- internal/oidc/discovery.go
- internal/oidc/discovery_test.go
While working on https://github.com/istio-ecosystem/authservice/pull/250, I saw that authservice was calling many times the well-known endpoint for a single OIDC session. This is because we call it when initializing the OIDC handlers, and that is done per request to the Envoy ext-authz filter, and a single OIDC session may involve several requests, given the redirects, making several unnecessary calls to the IdP.
This PR caches the seen well-known requests, and returns them from the cache for subsequent requests. The well-known endpoints are usually stable and it is very rare that they change, so it should be fine to just cache them by default.
> Cache well-known responses to avoid making too much calls to the IdP

- examples/minimal/authservice-config.yaml
- examples/minimal/authservice.yaml
- examples/minimal/authz-policy.yaml
- examples/minimal/istiod-values.yaml
- examples/minimal/oidc-intercept-policy.yaml
- examples/minimal/rbac.yaml
The only configs we had are the `e2e` ones, but it may be hard to get there when you're just trying to get started.
Having a minimal set of configs that are easy to copy/paste will be very helpful.
> Add minimal examples to make it easier to get started

- .github/workflows/scan.yaml
The upload job was not triggered int he scheduled scan, because the job was marked as failed.
This changes the config to only mark as failed the scans run as part of the PR checks.
> Fix scan job configuration

- .github/workflows/ci.yaml
- CODEOWNERS
- OWNERS
Update the code owners to the current active people, so that code reviews can happen in a timely manner.
It mgirates from the OWNERS file to GitHub CODEOWNERS. Once this is merged, a follow-up change will be done in `istio/test-infra` to update the Ci requirements accordingly.
@BrenoDeMedeiros @liminw @lizan @sawlanipradeep @incfly @Shikugawa you were listed in the OWNERS file, but as far as I know you're not active anymore in the project. Please leave a comment if you want to be kept in the CODEOWNERS file and I would be happy to add you before merging the PR. Thank you! :)
> Update code owners

- internal/file_test.go
The test method `waitForRead` was sometimes signaling due to accumulated reads, even it was inteded to wait for a read after a new content was set in the mock file.
This fixes it by waiting to singal read happened when the read content is the same as the expected one.
> Fix flaky file watcher test

- go.mod
There are some low CVEs reported in Go 1.22.2. This PR upgrades to the latest Go version to see if they're already fixed there.
https://github.com/istio-ecosystem/authservice/security/code-scanning
> Upgrade to Go 1.22.4

- go.mod
Ref: https://github.com/istio-ecosystem/authservice/security/code-scanning/6
See: https://groups.google.com/g/golang-dev/c/t0rK-qHBqzY/m/6MMoAZkMAgAJ
> Upgrade to Go 1.22.5 to fix CVE-2024-24791

- go.mod
Upgrade to Go 1.24.7 to fix CVE-2024-3566
> Upgrade to Go 1.24.7 to fix CVE-2024-3566
